version: '2'
services:
  prometheus-1:
    image: prom/prometheus:v1.7.1
    ports:
    - "19090:9090"
    restart: always
    command:
    - "-config.file=/etc/prometheus/prometheus.yml"
    - "-storage.local.path=/prometheus"
    - "-web.console.libraries=/etc/prometheus/console_libraries"
    - "-web.console.templates=/etc/prometheus/consoles"
    - "-web.listen-address=:9090"
    - "-alertmanager.url=http://alertmanager-1:9093,http://alertmanager-2:9093"

  prometheus-2:
    image: prom/prometheus:v1.7.1
    ports:
    - "29090:9090"
    restart: always
    command:
    - "-config.file=/etc/prometheus/prometheus.yml"
    - "-storage.local.path=/prometheus"
    - "-web.console.libraries=/etc/prometheus/console_libraries"
    - "-web.console.templates=/etc/prometheus/consoles"
    - "-web.listen-address=:9090"
    - "-alertmanager.url=http://alertmanager-1:9093,http://alertmanager-2:9093"

  alertmanager-1:
    image: prom/alertmanager:v0.7.1
    ports:
    - "29093:9093"
    restart: always
    # volumes:
    # - ./alertmanager/:/etc/alertmanager/
    # - ./storage/alertmanager/:/alertmanager
    command:
    - '-config.file=/etc/alertmanager/config.yml'
    - '-storage.path=/alertmanager'
    - '-mesh.peer=alertmanager-2:6783'

  alertmanager-2:
    image: prom/alertmanager:v0.7.1
    ports:
    - "19093:9093"
    restart: always
    # volumes:
    # - ./alertmanager/:/etc/alertmanager/
    # - ./storage/alertmanager/:/alertmanager
    command:
    - '-config.file=/etc/alertmanager/config.yml'
    - '-storage.path=/alertmanager'
    - '-mesh.peer=alertmanager-1:6783'


